pub mod text;
pub mod xml;

use crate::models::ParsedSitemap;
use text::parse_plain_text;

pub use text::parse_plain_text as parse_plain_text_sitemap;
pub use xml::{parse_datetime, parse_priority, parse_xml, parse_xml_limited};

/// Auto-detect XML vs. plain-text and parse.
///
/// Detection is prefix-tolerant: a UTF-8 BOM, leading whitespace, an XML
/// declaration, or an HTML/XML comment before `<urlset>` / `<sitemapindex>`
/// all still route to the XML parser.
pub fn parse_sitemap(content: &str) -> ParsedSitemap {
    let trimmed = content.trim_start_matches('\u{feff}').trim_start();
    if looks_like_xml_sitemap(trimmed) {
        parse_xml(trimmed)
    } else {
        ParsedSitemap::PlainText {
            urls: parse_plain_text(content),
        }
    }
}

fn looks_like_xml_sitemap(s: &str) -> bool {
    let head_end = 8192.min(s.len());
    let head = match s.get(..head_end) {
        Some(h) => h,
        None => {
            // `head_end` is always a char boundary because we only shrink on
            // a non-boundary (UTF-8: continuation bytes are 0x80-0xBF, and
            // 8192 may land mid-character). Walk back to the previous boundary.
            let mut end = head_end;
            while end > 0 && !s.is_char_boundary(end) {
                end -= 1;
            }
            match s.get(..end) {
                Some(h) => h,
                None => s,
            }
        }
    };
    let lower = head.to_ascii_lowercase();
    lower.contains("<urlset")
        || lower.contains("<sitemapindex")
        || lower.trim_start().starts_with("<?xml")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bom_plus_xml_decl_is_detected_as_xml() {
        let xml = "\u{feff}<?xml version=\"1.0\"?>\n<urlset><url><loc>https://example.com/</loc></url></urlset>";
        match parse_sitemap(xml) {
            ParsedSitemap::UrlSet { entries } => assert_eq!(entries.len(), 1),
            other => panic!("expected urlset, got {other:?}"),
        }
    }

    #[test]
    fn leading_comment_is_detected_as_xml() {
        let xml = "<!-- generated by cms -->\n<urlset><url><loc>https://example.com/x</loc></url></urlset>";
        match parse_sitemap(xml) {
            ParsedSitemap::UrlSet { entries } => assert_eq!(entries[0].loc, "https://example.com/x"),
            other => panic!("expected urlset, got {other:?}"),
        }
    }

    #[test]
    fn plain_text_not_confused_with_xml() {
        let txt = "https://example.com/a\nhttps://example.com/b\n";
        match parse_sitemap(txt) {
            ParsedSitemap::PlainText { urls } => assert_eq!(urls.len(), 2),
            other => panic!("expected plaintext, got {other:?}"),
        }
    }
}
